// "Exercício do dia": 124 técnicas práticas (ação concreta que o usuário
// pode fazer no próprio dia), derivadas dos mecanismos descritos nas cinco
// fontes do projeto: Manual Barkley (3ª ed.), Cartilha ABP-Alexa, IACAPAP e
// "Vencendo o TDAH Adulto" (Barkley & Benton) — esta última é a fonte mais
// rica em técnicas acionáveis (as "8 Regras" de autogestão cotidiana) e está
// fortemente representada aqui. Diferente do "Princípio do dia"
// (reflexão/conceito), cada item aqui é uma AÇÃO concreta.
//
// Nota editorial: nenhuma das fontes tem uma lista pronta de exercícios —
// cada item é uma tradução prática de um mecanismo clínico nomeado e
// rastreável à fonte indicada (não uma citação literal). Não substituem
// acompanhamento profissional. Regra do projeto: toda fonte precisa ser
// específica e real, nunca uma citação vaga como "síntese clínica geral".

var EXERCISES = [
  { text: "Antes de abrir qualquer aplicativo hoje, escreva à mão em um papel visível as 3 tarefas mais importantes do dia — não mais que 3. Externalizar a prioridade compensa a dificuldade de manter isso \"na cabeça\".", source: "Manual Barkley, cap. 7 (externalização)" },
  { text: "Escolha uma tarefa que você vem adiando e divida-a em pelo menos 4 passos bem pequenos, cada um com verbo de ação (\"abrir o documento\", \"escrever o primeiro parágrafo\"). Passos pequenos e concretos são mais fáceis de iniciar.", source: "Manual Barkley, cap. 7 (planejamento)" },
  { text: "Configure um timer visível (celular, relógio, ou até um copo com água) para uma tarefa que você vai fazer agora. Ver o tempo passando substitui o \"sentido de tempo\" interno que costuma falhar no TDAH.", source: "Manual Barkley, cap. 7 (percepção de tempo)" },
  { text: "Quando sentir vontade de responder algo com raiva ou impulsividade hoje, conte até 10 antes de agir ou espere ler de novo depois de 5 minutos. A pausa é um substituto externo para a inibição que não vem automaticamente.", source: "Manual Barkley, cap. 7 (inibição comportamental)" },
  { text: "Escolha um objeto que você usa todos os dias (chaves, carteira, óculos) e defina um único lugar fixo para ele. Deixe-o lá hoje mesmo. Um \"lar\" fixo reduz a carga de memória para lembrar onde as coisas estão.", source: "Manual Barkley, cap. 7 · Cartilha ABP/Alexa" },
  { text: "Ao terminar uma tarefa hoje, dê a si mesmo uma recompensa pequena e imediata (um café, 5 minutos de algo que gosta) antes de passar para a próxima. Recompensa atrasada tem pouco efeito — o reforço precisa ser rápido.", source: "Manual Barkley, cap. 12 (reforço imediato)" },
  { text: "Escolha uma transição do seu dia (sair de casa, começar a trabalhar, ir dormir) e crie um alerta sonoro ou visual 10 minutos antes dela. Transições são pontos de risco de \"travar\"; um aviso externo ajuda a se preparar.", source: "Manual Barkley, cap. 7 (transição de tarefas)" },
  { text: "Antes de começar a trabalhar hoje, guarde fisicamente (numa gaveta, outro cômodo) uma fonte de distração específica. Reduzir estímulos concorrentes no ambiente é mais eficaz do que só confiar na força de vontade.", source: "Manual Barkley, cap. 7 · Cartilha ABP/Alexa" },
  { text: "Escolha uma tarefa chata de hoje e diga em voz alta, para si mesmo, o próximo passo antes de fazê-lo. Verbalizar o passo imita a \"fala interna\" que orienta o comportamento e que costuma ser menos eficaz no TDAH.", source: "Manual Barkley, cap. 3 (autoconversa/fala internalizada)" },
  { text: "Hoje, ao perceber que está enrolando com uma tarefa, anote a hora em que começou a enrolar e a hora em que efetivamente começou. Só observar essa diferença já ajuda a construir noção real de tempo, sem se julgar.", source: "Manual Barkley, cap. 7 (percepção de tempo)" },
  { text: "Escolha um compromisso que costuma esquecer e cadastre agora um alarme ou lembrete com o texto exato do que fazer. Lembretes automáticos substituem a memória prospectiva, um ponto fraco comum no TDAH.", source: "Cartilha ABP/Alexa (recursos tecnológicos de suporte)" },
  { text: "Antes de dormir hoje, deixe visível, perto da porta, os itens que precisa levar amanhã. Preparar à noite tira a decisão de cima da manhã, quando a autorregulação costuma estar mais fragilizada.", source: "Manual Barkley, cap. 7 (externalização)" },
  { text: "Se hoje você perceber que está prestes a interromper alguém no meio da fala, tente segurar por 3 segundos antes de falar. Esse intervalo é treino direto de inibição de resposta.", source: "Manual Barkley, cap. 7 (inibição comportamental)" },
  { text: "Escolha uma tarefa longa e use um bloco curto de tempo (15–25 minutos) com um intervalo garantido depois. Blocos curtos com pausa reduzem a fadiga da atenção sustentada, que se esgota mais rápido no TDAH.", source: "Manual Barkley, cap. 7 (atenção sustentada)" },
  { text: "Hoje, ao sentir uma emoção forte, nomeie-a em voz alta ou por escrito (\"estou irritado porque isso demorou\") antes de reagir. Nomear a emoção ativa uma pausa entre sentir e agir.", source: "Manual Barkley, cap. 7 (autorregulação emocional)" },
  { text: "Escolha um cômodo ou mesa de trabalho e remova, só por hoje, tudo que não é necessário para a tarefa atual. Menos objetos no campo visual, menos \"ganchos\" para a atenção sair do lugar.", source: "Manual Barkley, cap. 7 · Cartilha ABP/Alexa" },
  { text: "Antes de sair de casa hoje, faça uma checagem verbal em voz alta dos itens essenciais (\"chave, carteira, celular\"). Rotinas verbais fixas reduzem esquecimentos recorrentes sem exigir memória perfeita.", source: "Manual Barkley, cap. 3 (autoconversa)" },
  { text: "Escolha uma tarefa chata e negocie consigo mesmo um \"custo\" se não a fizer até um horário combinado (ex: não checar redes sociais até terminar). Perder algo de valor costuma motivar mais do que só \"tentar lembrar\".", source: "Manual Barkley, cap. 12 (custo de resposta)" },
  { text: "Hoje, ao acordar, evite checar o celular nos primeiros 10 minutos e escreva uma frase sobre como quer que o dia comece. Adiar o estímulo mais absorvente do dia dá espaço para autorregulação antes da sobrecarga.", source: "Manual Barkley, cap. 7 (autorregulação)" },
  { text: "Escolha uma tarefa que você tende a fazer de forma impulsiva e escreva 2 linhas antes de começar: \"o que eu quero no final\" e \"primeiro passo\". Isso é um exercício direto de planejamento.", source: "Manual Barkley, cap. 7 (planejamento)" },
  { text: "Se hoje surgir um pensamento do tipo \"eu devia conseguir fazer isso sem ajuda\", anote-o e responda por escrito com um fato: TDAH tem base neurobiológica, não é falta de esforço. Contestar o mito por escrito ajuda a lembrar que isso não é uma falha pessoal.", source: "Manual Barkley, cap. 5 · Cartilha ABP/Alexa" },
  { text: "Escolha um horário fixo para dormir hoje e configure um alarme \"hora de desligar telas\" 30 minutos antes. Sono irregular piora diretamente atenção e controle de impulsos no dia seguinte.", source: "Manual Barkley, cap. 3 (sono e TDAH)" },
  { text: "Hoje, ao iniciar uma tarefa, deixe visível só o material daquela tarefa específica na mesa. Reduzir pistas de outras tarefas evita a troca constante de foco.", source: "Manual Barkley, cap. 7 (controle de estímulos)" },
  { text: "Escolha uma pessoa (parceiro, amigo, familiar, colega) e peça a ela para te lembrar de um compromisso específico hoje. Apoio social como lembrete externo é uma forma legítima de compensar déficits de memória.", source: "Cartilha ABP/Alexa (apoio social no manejo)" },
  { text: "Se hoje você perceber que uma tarefa está tomando muito mais tempo do que devia, pare e pergunte por escrito: \"isso ainda é necessário ou eu travei em detalhe?\". Essa pausa quebra o padrão de atenção presa numa tarefa que engancha (\"hiperfoco\", termo não usado literalmente pelas fontes, mas o padrão de atenção variável conforme motivação é descrito no Cap. 7).", source: "Manual Barkley, cap. 7 (persistência voltada a objetivos)" },
  { text: "Escolha uma meta pequena de hoje e, assim que cumprir, marque com um \"X\" visível em um papel ou aplicativo. Ver o progresso registrado dá um reforço visual imediato que a mente por si só não retém bem.", source: "Manual Barkley, cap. 12 (reforço visual)" },
  { text: "Antes de uma reunião, compromisso ou conversa importante hoje, escreva 2 ou 3 pontos que quer lembrar de dizer. Isso externaliza o \"roteiro mental\" que costuma se perder no meio da fala espontânea.", source: "Manual Barkley, cap. 3 (memória de trabalho verbal)" },
  { text: "Hoje, ao sentir o impulso de começar uma tarefa nova antes de terminar a atual, escreva a nova ideia numa lista de \"depois\" em vez de trocar de tarefa na hora. A lista captura o impulso sem exigir força de vontade.", source: "Manual Barkley, cap. 7 (inibição comportamental)" },
  { text: "Escolha um momento do dia para se mover fisicamente por 5 minutos (caminhar, alongar, subir escada) antes de uma tarefa que exige concentração. Atividade física breve ajuda a regular o estado de alerta.", source: "Manual Barkley, cap. 7 (regulação do estado de alerta)" },
  { text: "Hoje, ao terminar o dia, escreva uma coisa que deu certo, mesmo pequena — não o que faltou fazer. Fechar o dia notando progresso contraria o viés de autocrítica comum em quem convive com TDAH há anos.", source: "Manual Barkley, cap. 3 (autoestima e histórico de vida)" },
  { text: "Escolha uma regra ou combinado que você tem com alguém e, hoje, transforme-a em um lembrete visual físico (post-it, cartaz, nota na porta) em vez de depender de lembrar sozinho. Regras visíveis no ambiente funcionam melhor.", source: "Manual Barkley, cap. 7 · Cartilha ABP/Alexa" },

  { text: "Hoje, ao sentir vontade de responder no calor do momento (mensagem, e-mail, discussão), pare fisicamente por 3 segundos antes de agir: respire fundo uma vez e só depois decida. Regra 1 de \"Vencendo o TDAH Adulto\" (Passo 4) — criar uma pausa física é o substituto externo do freio que não vem automaticamente.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 1" },
  { text: "Antes de responder a uma pergunta difícil hoje, repita em voz baixa o que a outra pessoa disse antes de formular sua resposta. Repetir ganha tempo e ativa a Regra 1 (Pare a ação) de \"Vencendo o TDAH Adulto\" na comunicação.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 1" },
  { text: "Escolha uma situação de hoje em que você normalmente reagiria rápido demais (dirigir, discutir, decidir uma compra) e treine falar mais devagar de propósito, mesmo que pareça estranho. \"Vencendo o TDAH Adulto\" descreve falar mais devagar como técnica prática da Regra 1 para criar espaço de inibição.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 1" },
  { text: "Hoje, antes de mandar aquela mensagem ou e-mail que você escreveu com raiva, deixe o rascunho salvo e releia só depois de 15 minutos. Regra 1 (Pare a ação) de \"Vencendo o TDAH Adulto\": o intervalo físico entre impulso e ação é o que falta naturalmente no TDAH.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 1" },
  { text: "Escolha um momento hoje em que perceber tensão subindo numa conversa e proponha uma pausa de verdade (\"posso te responder em 5 minutos?\") em vez de continuar no automático. A Regra 1 trata a pausa como ferramenta ativa, não como fraqueza.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 1" },
  { text: "Antes de tomar uma decisão de compra hoje (mesmo pequena), pare e conte até 10 olhando para o produto antes de decidir. Aplicação direta da Regra 1 de \"Vencendo o TDAH Adulto\" ao consumo impulsivo.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 1" },
  { text: "Hoje, ao dirigir, treine uma pausa deliberada de 1 segundo antes de acelerar em um sinal amarelo ou entrar numa vaga apertada. \"Vencendo o TDAH Adulto\" (Passo 5, Direção) recomenda usar a Regra 1 especificamente no trânsito, onde a impulsividade tem custo mais alto.", source: "Vencendo o TDAH Adulto, Passo 5 · Direção (Regra 1)" },
  { text: "Escolha uma tarefa nova que te chamou atenção hoje e, antes de começá-la, pare e pergunte: \"isso é mais importante que o que eu já estava fazendo?\". A Regra 1 existe para interromper o piloto automático antes que ele te desvie do plano.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 1" },
  { text: "Antes de decidir algo hoje (uma resposta, uma compra, uma tarefa nova), pare 30 segundos e lembre de uma vez em que uma decisão parecida deu certo ou errado. Regra 2 de \"Vencendo o TDAH Adulto\" — olhar para o passado antes de agir compensa a fraqueza da memória de trabalho não-verbal (o \"olho da mente\").", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 2" },
  { text: "Escolha uma situação de hoje parecida com algo que você já viveu antes (uma reunião, um conflito, uma tarefa complexa) e escreva 2 linhas lembrando como foi da última vez, antes de agir de novo. Isso treina diretamente a função de memória de trabalho não-verbal descrita no Cap. 7 do Manual Barkley.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 2" },
  { text: "Antes de se comprometer com algo hoje, imagine concretamente como você vai se sentir daqui a 1 hora fazendo aquilo. Regra 2 (olhar para o futuro) de \"Vencendo o TDAH Adulto\" usa visualização para compensar a \"cegueira temporal\" descrita no modelo de Barkley.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 2" },
  { text: "Escolha uma tarefa chata de hoje e, antes de começar, visualize por 30 segundos como vai se sentir quando ela estiver pronta. \"Considere o futuro\" (Regra 5) usa a sensação antecipada de alívio como combustível motivacional.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 5" },
  { text: "Hoje, antes de uma decisão importante, pergunte a si mesmo em voz alta: \"da última vez que fiz algo parecido, o que funcionou e o que não funcionou?\". Regra 2 de \"Vencendo o TDAH Adulto\" transforma a experiência passada em critério ativo de decisão, já que ela não vem à mente sozinha.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 2" },
  { text: "Escolha algo que você vai fazer amanhã e, hoje à noite, imagine em detalhe como será o momento de terminar essa tarefa amanhã. Visualizar o futuro concluído (Regra 2/5) compensa a memória de trabalho não-verbal fraca que dificulta prever consequências.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 2 e 5" },
  { text: "Antes de recusar ou aceitar um convite hoje, pare e lembre de uma ocasião parecida no passado — funcionou bem ou mal? Regra 2 de \"Vencendo o TDAH Adulto\": usar o passado como referência explícita, não deixar a decisão só no impulso do momento.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 2" },
  { text: "Escolha uma tarefa que você vem evitando e diga em voz alta, sozinho, o que vai fazer e por quê, como se estivesse explicando para outra pessoa. Regra 3 (\"Expresse o passado e o futuro\") de \"Vencendo o TDAH Adulto\" usa a fala verbalizada para compensar a fraqueza da memória de trabalho verbal (a \"voz da mente\").", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 3" },
  { text: "Hoje, antes de uma tarefa complexa, narre em voz alta os passos que você vai seguir, como se fosse um tutorial falado para si mesmo. Verbalizar o plano é a aplicação prática da Regra 3, que substitui a autoconversa interna que costuma falhar no TDAH.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 3" },
  { text: "Escolha uma regra que você quer seguir hoje (\"vou checar e-mail só 3 vezes\") e diga essa regra em voz alta para si mesmo antes de começar o dia. Regra 3 de \"Vencendo o TDAH Adulto\" trata formular regras em voz alta como mais eficaz do que só pensá-las.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 3" },
  { text: "Depois de terminar uma tarefa hoje, fale em voz alta (ou grave um áudio curto) o que funcionou e o que você faria diferente da próxima vez. Regra 3 transforma a experiência em uma regra verbalizada explícita, já que a reflexão silenciosa tende a se perder.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 3" },
  { text: "Antes de uma ligação ou conversa difícil hoje, ensaie em voz alta, sozinho, o que você quer dizer. \"Vencendo o TDAH Adulto\" liga isso à memória de trabalho verbal fraca: verbalizar antes ajuda a manter a sequência lógica na hora de falar de verdade.", source: "Vencendo o TDAH Adulto, seção sobre comunicação (Regra 3)" },
  { text: "Escolha uma tarefa que exige planejamento hoje e narre para si mesmo, em voz alta, cada etapa antes de fazê-la (\"agora eu abro o arquivo, depois reviso o título...\"). Regra 3 substitui a fala interna que orienta a ação, ponto fraco descrito no Cap. 7 do Manual Barkley.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 3" },
  { text: "Escolha um compromisso de amanhã e escreva um lembrete físico (post-it, cartão) e coloque-o exatamente no lugar onde você vai precisar dele (na porta, no volante, na tela do notebook). Regra 4 (\"Exteriorize as informações fundamentais\") de \"Vencendo o TDAH Adulto\" — o lembrete precisa estar no ponto de ação, não só guardado num app.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 4" },
  { text: "Hoje, comece (ou retome) um caderno ou bloco de notas físico que fique sempre com você, e anote nele qualquer compromisso ou ideia importante assim que surgir. Regra 4 recomenda um diário sempre à mão como externalização contínua da memória de trabalho.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 4" },
  { text: "Escolha uma informação que você tende a esquecer (senha de um sistema, medida de uma receita, horário de um remédio) e cole um lembrete físico visível exatamente onde você vai usá-la. \"Vencendo o TDAH Adulto\" enfatiza que o lembrete só funciona se estiver no local certo, não em qualquer lugar.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 4" },
  { text: "Hoje, transforme uma regra combinada (com parceiro, filho ou equipe) em um cartaz ou nota física visível no ambiente, em vez de confiar só na memória de todos. Regra 4 de \"Vencendo o TDAH Adulto\" aplicada a combinados familiares ou de trabalho.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 4" },
  { text: "Antes de sair para uma tarefa fora de casa hoje, escreva num papel os 3 itens ou informações que não pode esquecer e leve o papel com você, não só na cabeça. Exteriorizar as informações fundamentais (Regra 4) reduz a dependência da memória de trabalho.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 4" },
  { text: "Escolha uma tarefa grande de hoje ou da semana e escreva, num só papel visível, apenas o próximo passo concreto — não a lista toda. Regra 4 recomenda deixar visível só a informação necessária no momento certo, para não sobrecarregar.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 4" },
  { text: "Hoje, se você tem uma reunião ou compromisso importante, escreva os pontos-chave num cartão pequeno e mantenha-o visível durante a conversa. \"Vencendo o TDAH Adulto\" recomenda essa exteriorização para compensar a memória de trabalho verbal na comunicação.", source: "Vencendo o TDAH Adulto, seção sobre comunicação (Regra 4)" },
  { text: "Escolha uma tarefa grande que você vem adiando e, antes de começar, imagine e escreva uma frase sobre como vai se sentir ao finalmente terminá-la. Regra 5 (\"Considere o futuro\") de \"Vencendo o TDAH Adulto\" usa a antecipação emocional da conclusão como motivação, já que a recompensa distante normalmente não motiva no TDAH.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 5" },
  { text: "Hoje, antes de uma tarefa chata, escreva por escrito a resposta para: \"o que eu ganho de verdade quando isso estiver pronto?\". Regra 5 transforma um benefício abstrato e distante em algo concreto e sentido agora.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 5" },
  { text: "Escolha algo que você tem evitado fazer por semanas e descreva por escrito, em detalhe, a cena de você tendo terminado — o que vai sentir, o que vai poder fazer depois. \"Considere o futuro\" (Regra 5) usa a imaginação vívida como substituto do planejamento natural que falha no TDAH.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 5" },
  { text: "Antes de decidir gastar ou economizar hoje, imagine concretamente uma cena futura de usar (ou não ter) esse dinheiro depois. \"Vencendo o TDAH Adulto\" (Passo 5, Dinheiro) aplica a Regra 5 diretamente a decisões financeiras.", source: "Vencendo o TDAH Adulto, Passo 5 · Dinheiro (Regra 5)" },
  { text: "Hoje, escolha uma meta de médio prazo (semana ou mês) e escreva uma frase descrevendo a cena de tê-la alcançado, com o máximo de detalhe sensorial possível. Regra 5 recomenda tornar o futuro vívido o suficiente para competir com a gratificação imediata.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 5" },
  { text: "Escolha uma tarefa grande que está te paralisando hoje e divida-a em pelo menos 5 blocos pequenos, cada um com um prazo próprio, ainda que informal. Regra 6 (\"Decomponha o futuro e o torne significativo\") de \"Vencendo o TDAH Adulto\" — tarefas grandes de prazo distante não geram ação no TDAH, só blocos pequenos com prazo próximo geram.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 6" },
  { text: "Hoje, escolha uma etapa de uma tarefa maior e combine com alguém (colega, amigo, parceiro) que você vai mostrar o resultado até um horário específico. Regra 6 usa prestação de contas a terceiros como reforço externo para cumprir prazos intermediários.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 6" },
  { text: "Escolha uma tarefa longa de hoje e, a cada etapa concluída, dê a si mesmo algo bom na hora — um lanche, uma pausa, uma mensagem de parabéns a si mesmo. Regra 6 recomenda recompensa imediata a cada bloco pequeno, não só ao final do projeto inteiro.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 6" },
  { text: "Hoje, pegue uma meta grande da semana e escreva-a como uma sequência de passos com prazo de horas, não de dias. \"Decomponha o futuro\" (Regra 6) torna prazos distantes significativos ao aproximá-los da percepção imediata de tempo.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 6" },
  { text: "Escolha uma tarefa de estudo ou trabalho longa hoje e defina, antes de começar, um ponto de checagem no meio do caminho onde alguém vai perguntar como está indo. \"Vencendo o TDAH Adulto\" (Passo 5, Estudo) recomenda parceiros de estudo com checagens frequentes como aplicação da Regra 6.", source: "Vencendo o TDAH Adulto, Passo 5 · Educação (Regra 6)" },
  { text: "Hoje, escolha um projeto pessoal parado há tempo e quebre só a primeira semana dele em passos diários bem pequenos, sem se preocupar ainda com o resto. Regra 6 foca em tornar significativo o próximo passo, não o projeto inteiro de uma vez.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 6" },
  { text: "Escolha um problema real que está te incomodando hoje e escreva-o fisicamente num papel, com uma caneta, em vez de só remoê-lo mentalmente. Regra 7 (\"Torne os problemas externos, físicos e manuais\") de \"Vencendo o TDAH Adulto\" — resolver mentalmente é mais difícil no TDAH; colocar no papel ajuda a manipular a informação de fora para dentro.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 7" },
  { text: "Hoje, use um quadro, post-its coloridos ou cartões físicos para organizar as tarefas do dia, em vez de manter tudo só na cabeça ou num app que você não olha. Regra 7 recomenda ferramentas visuais e manuais como extensão física do planejamento.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 7" },
  { text: "Escolha uma decisão difícil de hoje (duas opções concorrentes) e escreva fisicamente os prós e contras de cada lado em colunas separadas no papel. Regra 7 de \"Vencendo o TDAH Adulto\" transforma um dilema mental em algo manipulável fora da cabeça.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 7" },
  { text: "Hoje, ao organizar seu espaço de trabalho, use etiquetas físicas ou cores para categorizar documentos ou tarefas, em vez de confiar só em memorizar onde cada coisa está. Aplicação prática da Regra 7 (tornar os problemas físicos e manuais).", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 7" },
  { text: "Escolha um conflito ou mal-entendido de hoje e, antes de resolvê-lo na conversa, escreva num papel o que você quer dizer e em que ordem. Regra 7 recomenda usar ferramentas físicas mesmo em situações interpessoais, não só em tarefas de trabalho.", source: "Vencendo o TDAH Adulto, Passo 5 · Relacionamentos (Regra 7)" },
  { text: "Hoje, se cometer um erro (esquecer algo, chegar atrasado, perder um prazo), reconheça em voz alta com leveza (\"lá vou eu de novo\") em vez de se punir ou negar o erro. Regra 8 (\"Tenha senso de humor\") de \"Vencendo o TDAH Adulto\" trata o humor autodepreciativo saudável como parte do manejo, evitando tanto a negação quanto a culpa excessiva.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 8" },
  { text: "Escolha um erro recente causado por um sintoma do TDAH e pratique hoje as 4 etapas da Regra 8: reconhecer o que houve, explicar (não justificar), pedir desculpas se necessário, e dizer o que vai tentar diferente da próxima vez.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 8" },
  { text: "Hoje, ao perceber que esqueceu algo pela enésima vez, ria da situação por um segundo antes de corrigir o problema, sem transformar isso em autocrítica pesada. \"Vencendo o TDAH Adulto\" descreve o senso de humor como proteção contra a vergonha crônica, sem minimizar o impacto real do sintoma.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 8" },
  { text: "Escolha uma situação em que você atrapalhou algo hoje (ou recentemente) por impulsividade e conte essa história para alguém de confiança com leveza, sem se rebaixar. Regra 8 recomenda compartilhar os deslizes com humor como forma de aliviar a carga emocional acumulada.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 8" },
  { text: "Hoje, antes de dormir, escolha um erro do dia causado por esquecimento ou impulsividade e escreva uma versão engraçada da cena, como se fosse contar para um amigo. Prática de humor autodepreciativo (Regra 8) que separa o erro da identidade da pessoa.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 8" },
  { text: "No trabalho hoje, identifique uma fonte de distração do seu espaço físico (barulho, tela cheia de abas, pessoas passando) e mude sua posição ou peça para reduzir esse estímulo por 1 hora. \"Vencendo o TDAH Adulto\" (Passo 5, Trabalho) recomenda adaptar o ambiente físico em vez de só tentar se concentrar mais.", source: "Vencendo o TDAH Adulto, Passo 5 · Trabalho" },
  { text: "Escolha uma tarefa de trabalho de hoje e, se possível, converse com um colega de confiança para que ele funcione como um \"check-in\" rápido no meio do dia, perguntando como está indo. Aplicação da ideia de mentor/parceiro no trabalho descrita em \"Vencendo o TDAH Adulto\" (Passo 5).", source: "Vencendo o TDAH Adulto, Passo 5 · Trabalho" },
  { text: "Hoje, antes de aceitar uma nova tarefa no trabalho, pare e avalie por escrito se ela é compatível com o tipo de ambiente/rotina em que você funciona melhor (mais estrutura vs. mais autonomia). \"Vencendo o TDAH Adulto\" recomenda escolher tarefas e ambientes de trabalho compatíveis com o próprio perfil, em vez de forçar um encaixe que não existe.", source: "Vencendo o TDAH Adulto, Passo 5 · Trabalho" },
  { text: "Escolha uma tarefa de trabalho chata de hoje e faça-a em um bloco de tempo, sem checar e-mail ou mensagens durante esse período combinado. Reduzir estímulos concorrentes no ambiente de trabalho é recomendação central de \"Vencendo o TDAH Adulto\" (Passo 5, Trabalho).", source: "Vencendo o TDAH Adulto, Passo 5 · Trabalho" },
  { text: "Hoje, automatize (ou agende para automatizar essa semana) o pagamento de uma conta fixa que você costuma esquecer ou atrasar. \"Vencendo o TDAH Adulto\" (Passo 5, Dinheiro) recomenda automatizar pagamentos para tirar a decisão financeira do momento presente, onde a impulsividade pesa mais.", source: "Vencendo o TDAH Adulto, Passo 5 · Dinheiro" },
  { text: "Escolha um gasto pequeno de hoje e pague em dinheiro físico, em vez de cartão, sentindo o valor sair fisicamente da carteira. \"Vencendo o TDAH Adulto\" recomenda dinheiro físico como forma de tornar o gasto mais concreto e visível do que um cartão.", source: "Vencendo o TDAH Adulto, Passo 5 · Dinheiro" },
  { text: "Hoje, deixe visível (num papel na geladeira, numa planilha aberta) quanto você já gastou essa semana, para acompanhar de forma concreta, não só mental. Orçamento visível é recomendação de \"Vencendo o TDAH Adulto\" (Passo 5, Dinheiro) para compensar a dificuldade de prever consequências financeiras futuras.", source: "Vencendo o TDAH Adulto, Passo 5 · Dinheiro" },
  { text: "Antes de fazer uma compra maior hoje, espere pelo menos algumas horas e reveja a decisão depois desse intervalo. Aplicação da Regra 1 (Pare a ação) especificamente a decisões financeiras, descrita em \"Vencendo o TDAH Adulto\" (Passo 5, Dinheiro).", source: "Vencendo o TDAH Adulto, Passo 5 · Dinheiro (Regra 1)" },
  { text: "Hoje, converse com seu parceiro ou parceira sobre um sintoma seu do TDAH que costuma ser mal-interpretado (esquecimento, interrupção na fala, atraso) e explique o mecanismo por trás dele, sem se justificar excessivamente. \"Vencendo o TDAH Adulto\" (Passo 5, Relacionamentos) descreve que sintomas de TDAH são frequentemente confundidos com desinteresse ou grosseria, e nomear isso ajuda o outro a reinterpretar o comportamento.", source: "Vencendo o TDAH Adulto, Passo 5 · Relacionamentos" },
  { text: "Escolha uma interação difícil de hoje com alguém próximo e aplique deliberadamente a Regra 1 (pare antes de reagir) e a Regra 3 (verbalize antes de responder) na conversa. \"Vencendo o TDAH Adulto\" recomenda usar as 8 Regras especificamente nas interações mais próximas, onde a impulsividade tem mais custo emocional.", source: "Vencendo o TDAH Adulto, Passo 5 · Relacionamentos" },
  { text: "Hoje, se você é pai/mãe ou cuidador, escreva com seu parceiro uma regra familiar simples e coloque-a visível na cozinha ou sala. \"Vencendo o TDAH Adulto\" (Passo 5, Paternidade) recomenda regras familiares visíveis e combinadas com o parceiro, não só faladas.", source: "Vencendo o TDAH Adulto, Passo 5 · Paternidade/Maternidade" },
  { text: "Escolha um horário hoje para fazer uma checagem rápida e programada dos seus filhos (ou de uma responsabilidade de cuidado), usando um timer, em vez de depender de lembrar sozinho. \"Vencendo o TDAH Adulto\" recomenda uso de timer para checagem periódica na paternidade, compensando falhas de memória prospectiva.", source: "Vencendo o TDAH Adulto, Passo 5 · Paternidade/Maternidade" },
  { text: "Antes de dirigir hoje, faça uma checagem física do cinto de segurança com um lembrete visual (adesivo, nota) se você costuma esquecer. \"Vencendo o TDAH Adulto\" (Passo 5, Direção) recomenda lembretes físicos específicos para segurança no trânsito.", source: "Vencendo o TDAH Adulto, Passo 5 · Direção" },
  { text: "Hoje, se for dirigir, guarde o celular fora de alcance (porta-luvas, bolsa no banco de trás) antes de ligar o carro. \"Vencendo o TDAH Adulto\" recomenda bloquear o celular durante a direção como forma de eliminar a distração mais perigosa, em vez de confiar em resistir a ela.", source: "Vencendo o TDAH Adulto, Passo 5 · Direção" },
  { text: "Antes de uma sessão de estudo hoje, aplique a técnica SQ4R: examine o material (Survey), formule perguntas (Question) antes de ler, e só depois leia com atenção a essas perguntas. \"Vencendo o TDAH Adulto\" (Passo 5, Educação) recomenda SQ4R como técnica de leitura ativa que compensa a dificuldade de manter atenção sustentada em leitura passiva.", source: "Vencendo o TDAH Adulto, Passo 5 · Educação" },
  { text: "Hoje, antes de estudar algo importante, faça 10-15 minutos de atividade física (caminhada rápida, alongamento intenso) e comece o estudo logo em seguida. \"Vencendo o TDAH Adulto\" recomenda exercício físico antes de provas ou sessões de estudo para melhorar o estado de alerta.", source: "Vencendo o TDAH Adulto, Passo 5 · Educação" },
  { text: "Escolha uma matéria ou conteúdo que precisa estudar hoje e grave um áudio de você mesmo explicando o ponto principal, para ouvir depois. \"Vencendo o TDAH Adulto\" recomenda gravação como ferramenta de estudo, compensando a dificuldade de reter informação só lendo em silêncio.", source: "Vencendo o TDAH Adulto, Passo 5 · Educação" },
  { text: "Hoje, combine com um colega ou amigo um horário fixo de estudo em dupla, mesmo que cada um estude algo diferente, apenas para criar responsabilidade mútua. \"Vencendo o TDAH Adulto\" recomenda parceria de estudo como forma de prestação de contas externa (ligado à Regra 6).", source: "Vencendo o TDAH Adulto, Passo 5 · Educação (Regra 6)" },
  { text: "Hoje, escolha uma tarefa que exige memória de trabalho verbal (explicar algo complexo, escrever um texto) e faça um rascunho falado antes de escrever ou falar de verdade. Cap. 7 do Manual Barkley descreve a memória de trabalho verbal como responsável por manter a fala internalizada organizada; ensaiar em voz alta compensa essa fragilidade.", source: "Manual Barkley, cap. 7 (memória de trabalho verbal)" },
  { text: "Escolha uma tarefa hoje que dependa de prever passos futuros (planejar uma viagem, organizar um evento) e escreva por escrito, em ordem, cada etapa antes de agir. Isso treina diretamente a função de planejamento/resolução de problemas (o \"playground da mente\") descrita no Cap. 7 do Manual Barkley.", source: "Manual Barkley, cap. 7 (planejamento)" },
  { text: "Hoje, ao sentir uma frustração forte (algo deu errado, alguém te contrariou), escreva por escrito o que sente antes de decidir como vai reagir. O Cap. 7 do Manual Barkley descreve autorregulação do afeto como uma das 4 funções executivas comprometidas no TDAH; escrever cria a pausa que a regulação natural não oferece.", source: "Manual Barkley, cap. 7 (autorregulação emocional)" },
  { text: "Escolha uma tarefa que envolve múltiplas etapas simultâneas hoje (cozinhar algo com vários passos, organizar um evento) e use fichas físicas numeradas para cada etapa, movendo-as conforme avança. Exercício de planejamento/reconstituição (Cap. 7, Manual Barkley), usando apoio físico para compensar a função executiva mais fraca.", source: "Manual Barkley, cap. 7 (planejamento)" },
  { text: "Hoje, ao perceber uma emoção intensa subindo (raiva, ansiedade, frustração), experimente uma técnica de respiração de 4 tempos (inspirar 4s, segurar 4s, expirar 4s) antes de agir. A Cartilha ABP/Alexa descreve o TDAH como transtorno de autorregulação (não só de atenção); técnicas de regulação fisiológica ajudam diretamente nesse ponto.", source: "Cartilha ABP/Alexa (autorregulação)" },
  { text: "Escolha uma situação hoje em que você tende a se irritar rápido e, antes de reagir, escreva uma frase nomeando a emoção e sua intensidade de 0 a 10. Autorregulação emocional é uma das 4 funções executivas do modelo de Barkley (Cap. 7); medir a intensidade cria distância entre sentir e agir.", source: "Manual Barkley, cap. 7 (autorregulação emocional)" },
  { text: "Hoje, escolha uma tarefa e faça-a durante um bloco de tempo sem nenhuma notificação do celular ativa (modo avião ou não perturbe). A Cartilha ABP/Alexa descreve o uso de recursos tecnológicos como suporte externo às funções executivas — desligar notificações é a versão inversa: remover o estímulo que compete com o foco.", source: "Cartilha ABP/Alexa (recursos tecnológicos de suporte)" },
  { text: "Escolha uma rotina que você tem dificuldade de manter (horário de dormir, exercício, refeições) e configure um lembrete por assistente de voz ou app para hoje. A Cartilha ABP/Alexa recomenda especificamente assistentes de voz como suporte externo às funções executivas para rotinas.", source: "Cartilha ABP/Alexa (recursos tecnológicos de suporte)" },
  { text: "Hoje, se você usa medicação para TDAH, confira se tomou no horário certo e anote o horário num papel ou app, para ter esse dado se precisar ajustar com seu médico. Cap. 17 do Manual Barkley descreve efeitos dose-dependentes dos estimulantes; registrar horários ajuda no acompanhamento clínico, sem substituir orientação médica.", source: "Manual Barkley, cap. 17 (estimulantes)" },
  { text: "Escolha uma crença que você tem sobre si mesmo relacionada ao TDAH (\"sou preguiçoso\", \"não me esforço o suficiente\") e escreva ao lado um fato da Cartilha ABP/Alexa que contesta isso: TDAH tem herdabilidade de até 90% e não é causado por falta de esforço ou má criação.", source: "Cartilha ABP/Alexa (mitos desmontados)" },
  { text: "Hoje, se você tem TDAH e também sintomas de ansiedade, escolha uma tarefa e faça-a em passos menores que o habitual, já que ansiedade combinada a TDAH tende a aumentar a desatenção. O Cap. 4 do Manual Barkley descreve que ansiedade comórbida está associada a mais desatenção; passos menores reduzem a sobrecarga cognitiva.", source: "Manual Barkley, cap. 4 (comorbidades)" },
  { text: "Escolha uma situação social de hoje em que você tende a interpretar um comentário como hostil e, antes de reagir, pergunte por escrito: \"existe outra explicação possível para isso?\". O Cap. 16 do Manual Barkley descreve que pessoas com TDAH tendem a interpretar comportamento alheio como mais hostil do que é; essa pausa reduz reação desproporcional.", source: "Manual Barkley, cap. 16 (resolução de conflitos)" },
  { text: "Hoje, se você lida com irritabilidade ou baixa tolerância à frustração, escolha um momento do dia para uma atividade física curta (caminhada, alongamento) como forma de regular o estado de alerta antes de uma tarefa que exige paciência. Conecta-se à autorregulação emocional (Cap. 7, Manual Barkley) e à recomendação de exercício físico presente em \"Vencendo o TDAH Adulto\".", source: "Manual Barkley, cap. 7 · Vencendo o TDAH Adulto, Passo 5 (Educação)" },
  { text: "Escolha uma tarefa hoje que você tende a deixar para o fim do prazo e pergunte por escrito: \"o que essa procrastinação está me protegendo de sentir?\" antes de começar mesmo assim. Relacionado à miopia temporal do modelo de Barkley — nomear o motivo emocional ajuda a agir apesar dele.", source: "Vencendo o TDAH Adulto, Passo 2 (miopia temporal)" },
  { text: "Hoje, ao lidar com uma tarefa doméstica ou familiar repetitiva (louça, contas, remédios), crie um sistema de fichas simples: cada vez que concluir, mova um cartão de \"a fazer\" para \"feito\". Cap. 12 do Manual Barkley descreve o sistema de fichas como técnica comportamental eficaz para reforçar comportamento e torná-lo visível.", source: "Manual Barkley, cap. 12 (sistema de fichas)" },
  { text: "Escolha um comportamento que você quer reduzir hoje (procrastinar, checar celular em excesso) e defina um \"custo\" claro se ele acontecer (ex: perder um privilégio combinado). Cap. 12 do Manual Barkley descreve custo de resposta como técnica comportamental que funciona melhor com consequência imediata e clara, não vaga.", source: "Manual Barkley, cap. 12 (custo de resposta)" },
  { text: "Hoje, se você trabalha ou estuda com outras pessoas, negocie um sinal combinado (palavra, gesto) para avisar quando perceber que está se dispersando numa conversa ou reunião. Ajuda externa consciente, coerente com a recomendação da Cartilha ABP/Alexa de que apoio social é parte legítima do manejo, não uma muleta a evitar.", source: "Cartilha ABP/Alexa (apoio social no manejo)" },
  { text: "Escolha uma tarefa hoje que você tende a fazer de forma desorganizada e use cores diferentes (canetas, etiquetas, post-its) para categorizar as partes dela antes de começar. Aplicação da Regra 7 de \"Vencendo o TDAH Adulto\" (tornar problemas físicos e manuais) a uma tarefa de organização cotidiana.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 7" },
  { text: "Hoje, ao perceber que está prestes a evitar uma tarefa desconfortável (uma ligação, um formulário, uma conversa difícil), escreva por escrito: \"o que vai acontecer se eu não fizer isso hoje?\" antes de decidir adiar de novo. Usa a Regra 5 (Considere o futuro) de \"Vencendo o TDAH Adulto\" de forma negativa — antecipar a consequência de não agir, não só o benefício de agir.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 5" },
  { text: "Escolha uma meta que você tem para os próximos 3 meses e, hoje, escreva apenas o passo desta semana, ignorando o resto por enquanto. Regra 6 de \"Vencendo o TDAH Adulto\" — tornar o futuro significativo aproximando-o do presente, sem se perder no tamanho da meta inteira.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 6" },
  { text: "Hoje, se puder, peça a alguém de confiança para revisar com você uma decisão financeira ou de trabalho importante antes de fechá-la. \"Vencendo o TDAH Adulto\" (Passo 5, Dinheiro) menciona delegar ou compartilhar decisões financeiras como estratégia válida em casos de maior impulsividade, não como fraqueza.", source: "Vencendo o TDAH Adulto, Passo 5 · Dinheiro" },
  { text: "Escolha uma instrução complexa que você recebeu hoje (de um chefe, professor, médico) e peça para repetirem ou anote na hora, mesmo que pareça óbvio. \"Vencendo o TDAH Adulto\" recomenda pedir para repetir instruções complexas como forma de compensar a memória de trabalho verbal, não como falha de atenção.", source: "Vencendo o TDAH Adulto, seção sobre comunicação" },
  { text: "Hoje, se você está numa reunião ou aula, tome notas ativamente à mão, mesmo que depois não as releia. \"Vencendo o TDAH Adulto\" descreve que tomar notas ativamente ajuda a manter o foco no momento, não só a lembrar depois — o ato de escrever já é a ferramenta.", source: "Vencendo o TDAH Adulto, seção sobre comunicação" },
  { text: "Escolha uma tarefa doméstica ou de trabalho que você tende a fazer sozinho e sem prazo definido, e hoje combine com alguém um horário específico para mostrar o resultado. Regra 6 de \"Vencendo o TDAH Adulto\" — prestação de contas a terceiros transforma um prazo vago em um prazo real.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 6" },
  { text: "Hoje, antes de decidir se vai revelar seu diagnóstico de TDAH em algum contexto (trabalho, escola, relacionamento), escreva os prós e contras específicos dessa situação, sem regra geral. \"Vencendo o TDAH Adulto\" (Passo 5, Trabalho) recomenda revelar o diagnóstico apenas quando necessário para adaptações formais, avaliando caso a caso.", source: "Vencendo o TDAH Adulto, Passo 5 · Trabalho" },
  { text: "Escolha uma tarefa hoje em que você costuma se perder em detalhes sem terminar, e defina antes de começar um critério simples de \"pronto o suficiente\". Relacionado à função de planejamento (Cap. 7, Manual Barkley) — travar em detalhe é falha de reconstituição, não falta de esforço.", source: "Manual Barkley, cap. 7 (planejamento)" },
  { text: "Hoje, ao sentir que uma tarefa está demorando muito mais do que o esperado, escreva o horário de início e faça uma estimativa por escrito de quanto falta, comparando com a estimativa inicial. Treina diretamente a percepção de tempo, ligada à memória de trabalho não-verbal (Cap. 7, Manual Barkley).", source: "Manual Barkley, cap. 7 (percepção de tempo)" },
  { text: "Escolha um compromisso social de hoje (jantar, encontro, reunião informal) e prepare com antecedência 2 ou 3 tópicos de conversa por escrito, se costuma travar ao puxar assunto. Aplicação da Regra 4 (exteriorizar informações fundamentais) de \"Vencendo o TDAH Adulto\" à comunicação social.", source: "Vencendo o TDAH Adulto, seção sobre comunicação (Regra 4)" },
  { text: "Hoje, se algo te irritou e você já reagiu mal, pratique a Regra 8 (senso de humor) em etapas: reconheça o que houve para a pessoa envolvida, explique o motivo sem se justificar demais, peça desculpas se cabível, e diga o que vai tentar diferente da próxima vez.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 8" },
  { text: "Escolha uma área da sua vida (trabalho, estudo, relacionamento, dinheiro) onde os sintomas de TDAH mais te atrapalham hoje e aplique deliberadamente 2 das 8 Regras de \"Vencendo o TDAH Adulto\" nela ao longo do dia, anotando o que percebeu à noite.", source: "Vencendo o TDAH Adulto, Passo 4 (As 8 Regras)" }
];

/**
 * Retorna o exercício do dia correspondente à data informada (ou hoje).
 * Usa o dia do ano (1-366) como índice — mesmo esquema de principleForDate(),
 * necessário porque EXERCISES agora tem mais de 31 itens.
 * @param {Date} [date]
 * @returns {{text: string, source: string}}
 */
function exerciseForDate(date) {
  var d = date || new Date();
  var start = new Date(d.getFullYear(), 0, 0);
  var diff = d - start;
  var dayOfYear = Math.floor(diff / 86400000); // 1-366
  var index = (dayOfYear - 1) % EXERCISES.length;
  return EXERCISES[index];
}

export { EXERCISES, exerciseForDate };
