// "Princípio do dia": 124 textos curtos (reflexão/conceito educativo sobre
// TDAH), fundamentados nas cinco fontes do projeto: Manual Barkley (3ª ed.),
// Cartilha ABP/Alexa, capítulo IACAPAP, e "Vencendo o TDAH Adulto" (Barkley
// & Benton). Cada item traz o texto e a fonte específica que o embasa —
// regra do projeto: nenhum conteúdo clínico/educativo é exibido sem citar a
// fonte real (ver memória "sempre citar fonte"), nunca uma citação vaga como
// "síntese clínica geral". Muda de acordo com o dia do ano corrente (ver
// principleForDate), percorrendo todos os itens ao longo do ano.

var PRINCIPLES = [
  { text: "O cérebro com TDAH não sustenta bem informação, tempo e motivação internamente — a solução não é \"tentar mais\", é externalizar. Este checklist é isso aplicado à sua rotina real.", source: "Manual Barkley, cap. 7 · Cartilha ABP/Alexa" },
  { text: "Prazo que só existe na sua cabeça é prazo que não existe. Coloque hora, alarme ou lembrete visível — o cérebro com TDAH reage muito mais ao que vê do que ao que \"sabe\".", source: "Manual Barkley, cap. 7" },
  { text: "TDAH tem raiz genética forte, não é resultado de falta de caráter ou de má criação. Cobrar mais força de vontade de quem já está se esforçando só aumenta a frustração sem mudar o resultado.", source: "Manual Barkley, cap. 5 · Cartilha ABP/Alexa" },
  { text: "A dificuldade não é \"prestar atenção\" em geral — é sustentar atenção quando a tarefa não é interessante nem tem recompensa imediata. Torne a tarefa chata mais curta, mais visível ou com um prêmio pequeno no final.", source: "Manual Barkley, cap. 7 e cap. 12" },
  { text: "Memória de trabalho fraca significa que a informação \"escorrega\" antes de virar ação. Anotar não é frescura nem falta de inteligência — é a prótese que substitui um sistema que naturalmente falha.", source: "Manual Barkley, cap. 3 e cap. 7" },
  { text: "TDAH costuma vir com \"miopia temporal\": o futuro parece distante e pouco real, então o presente sempre ganha. Trazer a consequência futura para perto — visualizá-la, escrevê-la, antecipá-la — ajuda a competir com o impulso do agora.", source: "Manual Barkley, cap. 7" },
  { text: "Antes de reagir, existe uma fração de segundo em que era possível pausar. Treinar essa pausa — contar até três, respirar, sair da sala — é treinar o músculo que o TDAH deixa mais fraco.", source: "Manual Barkley, cap. 7" },
  { text: "Dificuldade para regular emoção faz parte do TDAH, não é \"drama\" ou instabilidade de caráter. Nomear o que você sente antes de agir já reduz a intensidade da resposta.", source: "Manual Barkley, cap. 7" },
  { text: "Recompensa que demora não segura a atenção de um cérebro com TDAH tanto quanto recompensa imediata. Quebrar uma meta grande em pequenas vitórias com retorno rápido não é fraqueza, é estratégia.", source: "Manual Barkley, cap. 7 e cap. 12" },
  { text: "Rotina fixa não é sobre disciplina moral — é sobre reduzir decisões. Cada decisão nova gasta energia que o cérebro com TDAH já tem em menor reserva.", source: "Manual Barkley, cap. 7 · Cartilha ABP/Alexa" },
  { text: "Começar uma tarefa costuma ser mais difícil do que executá-la. Se travar antes de iniciar, tente negociar consigo mesmo só os primeiros dois minutos — o resto costuma vir mais fácil depois.", source: "Manual Barkley, cap. 7" },
  { text: "Hiperfoco é a outra face do TDAH: a mesma dificuldade de regular atenção que atrapalha em tarefas chatas pode prender você por horas em algo que engancha. Use alarmes também para sair de tarefas boas demais, não só para lembrar das chatas.", source: "Manual Barkley, cap. 3 (Problemas Cognitivos Associados)" },
  { text: "Trocar de atividade exige uma função executiva que o TDAH enfraquece: desligar de uma coisa para ligar em outra. Um aviso de \"faltam 5 minutos\" antes da transição facilita esse desligamento.", source: "Manual Barkley, cap. 7" },
  { text: "TDAH raramente vem sozinho — ansiedade, transtorno opositor, alterações de humor e uso de substâncias são comorbidades frequentes. Se algo além da desatenção/impulsividade estiver pesando, vale investigar separadamente, não só rotular tudo como \"TDAH\".", source: "Cartilha ABP/Alexa · Manual Barkley, cap. 4 · IACAPAP" },
  { text: "Sono ruim piora sintomas de TDAH, e TDAH também dificulta manter um sono regular — é uma via de mão dupla. Proteger horário fixo de dormir é tão parte do manejo quanto qualquer lista de tarefas.", source: "Manual Barkley, cap. 3" },
  { text: "Adultos com TDAH costumam ter sido crianças com TDAH que aprenderam a mascarar sintomas, não pessoas que \"curaram\" o transtorno. Estratégias de organização continuam necessárias mesmo quando a hiperatividade visível diminuiu com a idade.", source: "Manual Barkley, cap. 6 · IACAPAP" },
  { text: "Muita gente com TDAH subestima o próprio nível de dificuldade — é um viés conhecido, não falta de autocrítica. Pedir feedback de alguém próximo sobre prazos e combinados pode revelar padrões que passam despercebidos por dentro.", source: "Manual Barkley, cap. 3" },
  { text: "Planejar um passo de cada vez é mais realista do que tentar visualizar o caminho inteiro de uma vez. Divida a tarefa em partes pequenas o suficiente para caber na memória de trabalho.", source: "Manual Barkley, cap. 7" },
  { text: "Custo de resposta — perder algo já conquistado por não cumprir um combinado — costuma funcionar melhor do que só prometer recompensa por bom comportamento. Pequenas perdas imediatas comunicam mais do que promessas distantes.", source: "Manual Barkley, cap. 12" },
  { text: "Impulsividade não é \"falta de educação\", é um freio que engata mais devagar. Ambientes com menos estímulo e menos tentação por perto reduzem a necessidade de exercer esse freio o tempo todo.", source: "Manual Barkley, cap. 7" },
  { text: "Lista de tarefas na cabeça compete com tudo que está acontecendo agora, e quase sempre perde. Colocar a lista fora da cabeça — papel, app, quadro — tira essa disputa e libera espaço mental.", source: "Manual Barkley, cap. 7 · Cartilha ABP/Alexa" },
  { text: "O tratamento eficaz do TDAH costuma combinar abordagem comportamental com acompanhamento profissional — não é escolher entre \"força de vontade\" ou \"remédio\", é somar estratégias que sustentam umas às outras.", source: "Cartilha ABP/Alexa · Manual Barkley, cap. 20 (estudo MTA)" },
  { text: "Um ambiente bagunçado ou barulhento pesa mais sobre um cérebro com TDAH do que sobre outros, porque ele já gasta mais energia filtrando estímulos. Reduzir bagunça visual ao redor da tarefa é reduzir a carga que a atenção precisa carregar.", source: "Manual Barkley, cap. 7 · Cartilha ABP/Alexa" },
  { text: "Autoinstrução verbal — \"falar\" o próximo passo em voz alta ou por escrito — supre uma função interna que no TDAH tende a ser mais fraca: a voz que guia o próprio comportamento. Narrar a tarefa em voz alta pode parecer bobo, mas ajuda a manter o rumo.", source: "Manual Barkley, cap. 3 e cap. 7" },
  { text: "TDAH tem base neurobiológica, não é invenção recente nem efeito colateral de tela ou tecnologia moderna. Isso não significa que telas não atrapalhem foco — significa que o transtorno já existia muito antes delas.", source: "Manual Barkley, cap. 5 · Cartilha ABP/Alexa" },
  { text: "Comemorar o progresso pequeno junto com o grande é importante: cérebros com TDAH respondem melhor a reforço frequente do que a uma única recompensa distante no fim de um grande projeto. Marque as vitórias intermediárias, não só a linha de chegada.", source: "Manual Barkley, cap. 7, 12 e 15" },
  { text: "Colocar objetos-chave sempre no mesmo lugar visível (chaves, carteira, remédio) elimina uma decisão e uma busca que, de outra forma, consomem atenção todos os dias. Ambiente previsível poupa função executiva para o que realmente importa.", source: "Manual Barkley, cap. 7 · Cartilha ABP/Alexa" },
  { text: "Errar um prazo ou esquecer um compromisso não é evidência de \"personalidade desorganizada\" — é sintoma esperado de um transtorno reconhecido, com explicação neurobiológica. Isso não tira sua responsabilidade sobre buscar apoio, mas tira o peso da culpa moral.", source: "Manual Barkley, cap. 5 · Cartilha ABP/Alexa" },
  { text: "Em crianças, TDAH costuma aparecer mais como agitação visível; em adultos, mais como inquietação interna, procrastinação e dificuldade de organização. O transtorno muda de forma ao longo da vida, não desaparece sozinho.", source: "Manual Barkley, cap. 6 · IACAPAP" },
  { text: "Dividir uma tarefa grande em etapas com prazos parciais imita, de fora, a função de planejamento que o TDAH dificulta por dentro. Cada etapa pequena vira um novo ponto de checagem e de ajuste de rota.", source: "Manual Barkley, cap. 7" },
  { text: "TDAH é tratado melhor como uma condição contínua a manejar, não como um problema a resolver de uma vez. Ajustar estratégias com o tempo — não desistir na primeira que falhou — é parte esperada do processo, não sinal de fracasso.", source: "Manual Barkley, cap. 7 · Cartilha ABP/Alexa" },

  { text: "O modelo de Barkley descreve quatro funções executivas que o TDAH enfraquece: a que visualiza passado e futuro (\"olho da mente\"), a que conversa consigo mesmo (\"voz da mente\"), a que regula emoção (\"coração da mente\") e a que planeja e testa opções (\"playground da mente\"). Cada dificuldade prática do dia a dia pode ser rastreada até uma dessas quatro.", source: "Vencendo o TDAH Adulto, Passo 2" },
  { text: "A memória de trabalho não verbal — o \"olho da mente\" — é o que permite reviver mentalmente uma situação parecida antes de agir de novo. Quando ela é fraca, cada decisão parece nova, mesmo que você já tenha vivido aquilo dez vezes antes.", source: "Vencendo o TDAH Adulto, Passo 2" },
  { text: "A \"voz da mente\" é a memória de trabalho verbal: a autoconversa interna que formula regras e mantém o fio da meada ao falar ou escrever. Quando ela falha, é comum perder o rumo no meio de uma explicação ou não achar as palavras na hora certa.", source: "Vencendo o TDAH Adulto, Passo 2 · seção sobre comunicação" },
  { text: "O \"coração da mente\" é a função executiva que regula a intensidade da emoção antes que ela vire ação. No TDAH, a emoção costuma chegar na mesma força de sempre, mas o controle sobre expressá-la ou não é que fica comprometido.", source: "Vencendo o TDAH Adulto, Passo 2" },
  { text: "O \"playground da mente\" é onde ideias e soluções seriam testadas mentalmente antes de agir. Quando essa função de planejamento é fraca, o caminho mais curto costuma ser agir primeiro e pensar depois — não por impulsividade de personalidade, mas por um passo que simplesmente não aconteceu por dentro.", source: "Vencendo o TDAH Adulto, Passo 2" },
  { text: "Barkley chama o TDAH de \"cegueira temporal\": não é que a pessoa não saiba o que precisa fazer no futuro, é que o futuro não pesa o suficiente agora para competir com o presente. É um problema de desempenho no momento certo, não de conhecimento.", source: "Vencendo o TDAH Adulto, Passo 2" },
  { text: "O livro descreve cinco áreas onde o TDAH adulto mais atrapalha: gerir tempo e metas, organizar e comunicar, manter autodisciplina diante de impulsos, se automotivar sem supervisão externa, e manter concentração e prontidão. Reconhecer em qual dessas áreas você mais tropeça ajuda a escolher a estratégia certa em vez de tentar tudo ao mesmo tempo.", source: "Vencendo o TDAH Adulto, Passo 2" },
  { text: "A primeira das oito regras de autogestão é simples de enunciar e difícil de praticar: pare a ação. Respirar, repetir o que a outra pessoa acabou de dizer, ou apenas falar mais devagar cria a fração de segundo que o TDAH costuma pular.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 1" },
  { text: "Antes de decidir algo, vale relembrar conscientemente uma situação parecida do passado e só depois imaginar o futuro decorrente da escolha atual. Essa é a segunda regra do livro: olhar para trás para poder olhar para frente com mais realismo.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 2" },
  { text: "Não basta visualizar o passado e o futuro por dentro — colocar isso em palavras, mesmo em voz alta e sozinho, ajuda a extrair dali uma regra prática para agora. É a terceira regra: expressar o passado e o futuro em vez de só senti-los vagamente.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 3" },
  { text: "A quarta regra de autogestão do livro é exteriorizar as informações fundamentais: lembretes físicos exatamente onde a ação vai acontecer, um caderno sempre à mão. A informação precisa estar no ambiente, porque contar só com a mente para guardá-la tende a falhar.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 4" },
  { text: "Antecipar emocionalmente como vai ser a sensação de ter terminado algo — não só pensar racionalmente sobre o prazo — é a quinta regra do livro: considerar o futuro como combustível motivacional, não só como dado abstrato.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 5" },
  { text: "A sexta regra propõe decompor o futuro em blocos pequenos e torná-lo significativo com prestação de contas a outra pessoa e recompensa imediata a cada etapa concluída. Tarefa grande sem essa fragmentação tende a ficar abstrata demais para gerar ação.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 6" },
  { text: "A sétima regra é tornar os problemas externos, físicos e manuais — post-its, quadros, fichas — em vez de tentar resolver tudo só na cabeça. O que está fora da mente compete melhor com as distrações do que o que fica só pensado.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 7" },
  { text: "A oitava e última regra do livro é ter senso de humor com os próprios erros: reconhecer o que aconteceu, explicar, pedir desculpas e prometer melhora — sem negação, mas também sem culpa excessiva. Humor autodepreciativo saudável é ferramenta de manejo, não fraqueza de caráter.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 8" },
  { text: "No trabalho, o livro recomenda escolher, sempre que possível, uma carreira e um ambiente compatíveis com o próprio perfil, além de reduzir distrações físicas no espaço. Revelar o diagnóstico ao empregador só costuma valer a pena quando é necessário para conseguir uma adaptação formal.", source: "Vencendo o TDAH Adulto, Passo 5 · Trabalho" },
  { text: "Em finanças, o livro sugere automatizar pagamentos, manter o orçamento visível e, em casos mais graves, delegar a administração do dinheiro a outra pessoa. Usar dinheiro físico em vez de cartão também ajuda porque torna o gasto concreto e visível no momento em que acontece.", source: "Vencendo o TDAH Adulto, Passo 5 · Dinheiro" },
  { text: "Em relacionamentos, sintomas de TDAH — esquecer, interromper, se distrair no meio de uma conversa — costumam ser mal-interpretados pelo outro como desinteresse ou grosseria. Aplicar as oito regras de autogestão nas interações e buscar tratamento tende a melhorar também a qualidade do relacionamento, não só os sintomas isolados.", source: "Vencendo o TDAH Adulto, Passo 5 · Relacionamentos" },
  { text: "Para quem tem TDAH e também é pai ou mãe, o livro recomenda tratar o próprio TDAH primeiro, antes de tentar impor regras aos filhos. Regras familiares visíveis, combinadas com o parceiro, e um timer para checagens periódicas ajudam a sustentar consistência que a memória sozinha não sustentaria.", source: "Vencendo o TDAH Adulto, Passo 5 · Paternidade/Maternidade" },
  { text: "Ao volante, o livro é direto: nunca dirigir sem a medicação em efeito quando ela é parte do tratamento, zero álcool, celular bloqueado, e um lembrete físico para o cinto de segurança. Direção exige exatamente as funções executivas mais afetadas pelo TDAH — antecipação, controle de impulso, atenção sustentada.", source: "Vencendo o TDAH Adulto, Passo 5 · Direção" },
  { text: "Comorbidades como transtorno opositor, transtorno de conduta, ansiedade e depressão aparecem em mais de 80% dos casos de TDAH adulto segundo o livro, e cada uma precisa de tratamento próprio além do manejo do TDAH em si. Tratar só a desatenção quando há uma comorbidade não resolvida deixa o quadro geral incompleto.", source: "Vencendo o TDAH Adulto, Passo 5 · Comorbidades" },
  { text: "Os critérios de avaliação propostos no livro são mais rigorosos que os critérios diagnósticos padrão: exigem sintomas em três áreas (atenção/persistência, controle de impulsos, atividade excessiva), início antes dos 16 anos e prejuízo em múltiplos domínios da vida — não só um incômodo pontual em um contexto específico.", source: "Vencendo o TDAH Adulto, Passo 1" },
  { text: "Cerca de 75% das pessoas respondem bem já ao primeiro estimulante testado, segundo o livro, mas o ajuste de dose é um processo gradual e monitorado, não algo definido de uma vez. Não estranhar se a primeira dose não for a ideal faz parte de esperar realisticamente pelo processo.", source: "Vencendo o TDAH Adulto, Passo 3" },
  { text: "Repetir em voz alta o que a outra pessoa acabou de dizer, antes de responder, ganha o tempo que a memória de trabalho verbal fraca não dá de graça. É uma das estratégias de comunicação mais simples descritas no livro, e serve tanto para não perder o fio quanto para mostrar que você escutou.", source: "Vencendo o TDAH Adulto, seção sobre comunicação" },
  { text: "Diagnosticar TDAH em adultos é mais complexo do que em crianças, porque depende de memória retrospectiva de sintomas da infância e se sobrepõe a outros quadros. O protocolo do Manual Barkley passa por quatro perguntas centrais: os sintomas existiam antes dos 12 anos? há prejuízo em mais de um ambiente da vida atual? outra condição explica melhor o quadro? existe comorbidade junto?", source: "Manual Barkley, cap. 11" },
  { text: "Um dos diagnósticos diferenciais mais importantes em adultos é distinguir TDAH de transtorno bipolar — os dois podem parecer parecidos de fora, mas pedem tratamentos diferentes. Por isso a avaliação de adultos costuma incluir triagem de humor e de uso de substâncias, não só escalas de atenção.", source: "Manual Barkley, cap. 11" },
  { text: "Nenhum teste isolado — nem de computador, nem neuropsicológico — confirma ou descarta TDAH sozinho, segundo o Manual Barkley. Testes servem para sustentar uma hipótese diagnóstica já levantada pela entrevista clínica, buscar explicações alternativas, ou identificar comorbidades associadas.", source: "Manual Barkley, cap. 9" },
  { text: "A entrevista com quem convive de perto é considerada a fonte mais rica de informação diagnóstica, mais até do que a entrevista direta sobre sintomas de desatenção e hiperatividade. Isso porque muita gente com TDAH tem dificuldade real de perceber e relatar o próprio padrão de comportamento.", source: "Manual Barkley, cap. 8" },
  { text: "Estimulantes agem bloqueando a recaptação de dopamina e noradrenalina no cérebro, o que ajuda a explicar por que melhoram atenção sustentada e controle de impulso. Estudos citados no Manual Barkley refutam a ideia de que o uso correto de estimulantes aumente risco de abuso de substâncias — o efeito, quando o tratamento é bem conduzido, tende a ser protetor.", source: "Manual Barkley, cap. 17" },
  { text: "Tiques não são mais considerados contraindicação absoluta para o uso de estimulantes, ao contrário do que se pensava antes — a decisão passou a ser individualizada, pesando benefício e efeito colateral caso a caso. Isso mostra como o entendimento sobre tratamento medicamentoso do TDAH segue sendo atualizado com novas evidências.", source: "Manual Barkley, cap. 17" },
  { text: "Quando estimulantes não são indicados — por ansiedade importante, tiques ou histórico de abuso de substâncias — a atomoxetina é uma alternativa não estimulante com eficácia comprovada em crianças, adolescentes e adultos, sem potencial de abuso.", source: "Manual Barkley, cap. 18" },
  { text: "O estudo MTA, um dos maiores já feitos sobre tratamento de TDAH, mostrou que combinar medicação com intervenção comportamental produz os melhores resultados gerais — com vantagem especialmente clara em desfechos como comportamento opositor e práticas parentais, além dos sintomas nucleares de atenção.", source: "Manual Barkley, cap. 20 · Estudo MTA" },

  { text: "TDAH raramente aparece sozinho: no livro \"Vencendo o TDAH Adulto\", Barkley estima que mais de 80% dos casos vêm acompanhados de outra condição — TOD, ansiedade, depressão ou uso de substâncias. Tratar só o TDAH e ignorar o resto costuma deixar a pessoa sem entender por que ainda se sente mal.", source: "Vencendo o TDAH Adulto (Barkley & Benton), Passo 5 — Comorbidades" },
  { text: "A \"cegueira temporal\" descrita por Barkley não é falta de inteligência sobre o futuro — é a dificuldade de fazer esse futuro pesar no momento da decisão. Saber que algo é importante e conseguir agir de acordo com isso são coisas diferentes no cérebro com TDAH.", source: "Vencendo o TDAH Adulto (Barkley & Benton), Passo 2" },
  { text: "Barkley organiza o TDAH em quatro funções executivas enfraquecidas: a \"voz da mente\" (memória de trabalho verbal), o \"olho da mente\" (memória de trabalho não verbal), o \"coração da mente\" (autocontrole emocional) e o \"playground da mente\" (planejamento). Entender qual dessas falha mais no seu dia ajuda a escolher a estratégia certa.", source: "Vencendo o TDAH Adulto (Barkley & Benton), Passo 2" },
  { text: "Antes de fechar um diagnóstico de TDAH, vale perguntar: os sintomas já apareciam antes dos 16 anos? Existe prejuízo em mais de uma área da vida? Alguma outra condição explica melhor o quadro? Essas são as perguntas centrais que o Manual Barkley recomenda para avaliação de adultos — não é intuição, é protocolo.", source: "Manual Barkley, cap. 11 (Avaliação de Adultos)" },
  { text: "Distinguir TDAH de transtorno bipolar em adultos é um dos diagnósticos diferenciais mais delicados: oscilação de humor no TDAH costuma ser rápida e reativa a eventos, enquanto no bipolar tende a formar episódios mais sustentados. Um profissional especializado é quem faz essa diferenciação com segurança.", source: "Manual Barkley, cap. 11 (Avaliação de Adultos)" },
  { text: "TDAH combinado com transtorno de conduta na infância indica, segundo os estudos longitudinais citados por Barkley, um subgrupo com maior risco de dificuldades persistentes na vida adulta — mas isso é estatística de grupo, não destino individual. Intervenção precoce muda essa trajetória.", source: "Manual Barkley, cap. 4 (Comorbidades) e cap. 6 (Curso evolutivo)" },
  { text: "Ansiedade associada ao TDAH tende a vir acompanhada de mais desatenção e, curiosamente, menos impulsividade — como se a preocupação excessiva funcionasse como um freio parcial. Isso mostra por que tratar só um sintoma isolado sem olhar o quadro completo pode confundir mais do que ajudar.", source: "Manual Barkley, cap. 4 (Comorbidades)" },
  { text: "O Projeto Milwaukee, um dos maiores estudos longitudinais sobre TDAH, acompanhou crianças até a vida adulta e mostrou que a persistência do transtorno varia bastante conforme o critério usado — mas os riscos em áreas como trânsito, trabalho e relacionamentos aparecem de forma consistente quando o TDAH não é manejado.", source: "Manual Barkley, cap. 6 (Curso evolutivo)" },
  { text: "A hiperatividade visível da infância — correr, subir, não parar quieto — tende a se transformar, na vida adulta, em inquietação interna: uma sensação constante de estar \"a mil\" por dentro, mesmo parado por fora. O transtorno muda de roupa, não desaparece.", source: "Manual Barkley, cap. 6 (Curso evolutivo) · IACAPAP" },
  { text: "TDAH em adultos está associado a maior risco de acidentes de trânsito, segundo dados citados no capítulo sobre curso evolutivo — não por imprudência de caráter, mas por falhas momentâneas de atenção sustentada e de inibição do impulso. Reconhecer esse risco é o primeiro passo para compensá-lo, não motivo de vergonha.", source: "Manual Barkley, cap. 6 (Curso evolutivo)" },
  { text: "A Regra 8 de Barkley para adultos com TDAH é \"tenha senso de humor\": reconhecer o erro, explicar sem se justificar excessivamente, pedir desculpas e seguir em frente, evitando tanto a negação quanto a culpa paralisante. É uma forma prática de proteger a autoestima sem deixar de assumir responsabilidade.", source: "Vencendo o TDAH Adulto (Barkley & Benton), Passo 4 — Regra 8" },
  { text: "Muitos adultos com TDAH carregam anos de rótulos como \"preguiçoso\", \"relaxado\" ou \"sem compromisso\" antes de qualquer diagnóstico. Esse histórico deixa marcas na autoestima que não somem só porque o diagnóstico chegou — costuma exigir um trabalho à parte de reconstrução da autoimagem.", source: "Vencendo o TDAH Adulto (Barkley & Benton), Passo 1 — Avaliação" },
  { text: "Em relacionamentos, sintomas de TDAH — esquecer combinados, interromper, se distrair no meio de uma conversa — são frequentemente interpretados pelo parceiro como desinteresse ou desrespeito. Nomear que é sintoma, não intenção, é o primeiro passo para tirar a culpa moral da equação sem tirar a responsabilidade de buscar tratamento.", source: "Vencendo o TDAH Adulto (Barkley & Benton), Passo 5 — Relacionamentos" },
  { text: "Adultos com TDAH não tratado enfrentam mais risco em áreas específicas da vida: dinheiro, direção, trabalho e relacionamentos aparecem repetidamente nos estudos como pontos de maior prejuízo. Isso não é acaso — são exatamente as áreas que mais exigem planejamento, memória de trabalho e controle de impulso sustentados no tempo.", source: "Vencendo o TDAH Adulto (Barkley & Benton), Passo 5" },
  { text: "TDAH tem base neurobiológica identificável: estudos de neuroimagem mostram maturação cortical cerca de três anos mais lenta e menor ativação de redes cerebrais frontais responsáveis por atenção e controle. Não é uma metáfora — é um atraso mensurável no desenvolvimento de circuitos específicos.", source: "Tratado IACAPAP, cap. D.1 — Neurobiologia" },
  { text: "Os sistemas de dopamina e noradrenalina — neurotransmissores ligados a motivação, recompensa e atenção — funcionam de forma diferente no cérebro com TDAH. É por isso que estimulantes, que atuam diretamente nesses sistemas, costumam ter efeito tão específico sobre os sintomas centrais.", source: "Tratado IACAPAP, cap. D.1 — Neurobiologia" },
  { text: "Nenhum exame de imagem ou biomarcador isolado confirma ou descarta TDAH — o diagnóstico continua sendo clínico, baseado em entrevista, histórico e relatos de múltiplas fontes. Achados de neuroimagem ajudam a entender o transtorno, não a diagnosticá-lo individualmente.", source: "Tratado IACAPAP, cap. D.1 — Diagnóstico" },
  { text: "Antes de fechar um diagnóstico de TDAH em criança, vale considerar se ela não é simplesmente uma das mais novas da turma: crianças relativamente mais imaturas por diferença de idade dentro do mesmo ano escolar são identificadas com TDAH com mais frequência — o chamado efeito de \"imaturidade relativa\".", source: "Tratado IACAPAP, cap. D.1 — Diagnóstico diferencial" },
  { text: "Trauma e negligência podem produzir sintomas parecidos com os do TDAH — desatenção, agitação, dificuldade de regulação — sem que o transtorno esteja presente. Diferenciar exige olhar a história de vida e o contexto, não só a lista de sintomas atuais.", source: "Tratado IACAPAP, cap. D.1 — Diagnóstico diferencial" },
  { text: "TDAH não tratado está associado a maior risco de acidentes, uso de substâncias e até mortalidade precoce — mas o mesmo corpo de pesquisa mostra que tratamento adequado reduz esses riscos de forma mensurável, incluindo menos acidentes de trânsito e menor risco de suicídio.", source: "Tratado IACAPAP, cap. D.1 — Curso e prognóstico" },
  { text: "Nem tudo no TDAH é déficit: a literatura também aponta traços associados a maior tolerância a risco, criatividade e perfil empreendedor em alguns adultos com o transtorno. Reconhecer isso não substitui o tratamento das dificuldades, mas ajuda a formar uma imagem mais completa e menos só negativa de si.", source: "Tratado IACAPAP, cap. D.1 — Curso e prognóstico" },
  { text: "TDAH em idosos existe e é frequentemente subdiagnosticado: a prevalência estimada em pessoas com 50 anos ou mais gira em torno de 1,5%, e sintomas de memória e desorganização às vezes são confundidos com outros quadros próprios da idade. É um transtorno que atravessa toda a vida, não uma condição só de infância ou juventude.", source: "Cartilha ABP/Alexa — Epidemiologia" },
  { text: "A proporção de diagnóstico entre homens e mulheres é maior nos consultórios do que na população em geral — cerca de 2,5 para 1 em amostras clínicas. Isso sugere que meninas e mulheres com TDAH são subidentificadas, provavelmente porque apresentam menos hiperatividade visível e mais sintomas internos, silenciosos.", source: "Cartilha ABP/Alexa — Diferenças de gênero · Manual Barkley, cap. 2" },
  { text: "Meninas com TDAH tendem a mostrar menos comportamento de oposição e agitação visível do que meninos, o que atrasa o encaminhamento para avaliação. O sintoma menos \"barulhento\" não significa menos prejuízo — só significa que passa mais despercebido.", source: "Manual Barkley, cap. 2 — Diferenças de gênero" },
  { text: "É mito que TDAH seja causado por má criação, excesso de tela ou açúcar — a herdabilidade genética do transtorno gira entre 70 e 90%, uma das mais altas entre os transtornos psiquiátricos. Fatores ambientais têm papel mediado e secundário, não causal isolado.", source: "Cartilha ABP/Alexa — Mitos desmontados · Tratado IACAPAP, cap. D.1 — Etiologia" },
  { text: "É mito que medicação para TDAH aumente o risco de uso de drogas no futuro — estudos mostram justamente o oposto: tratamento adequado com estimulantes está associado a um efeito protetor contra abuso de substâncias mais tarde na vida.", source: "Manual Barkley, cap. 17 (Estimulantes) · Cartilha ABP/Alexa — Mitos desmontados" },
  { text: "TDAH também tem histórico familiar frequente entre os pais: pesquisas mostram maior prevalência do próprio transtorno e de outros quadros psiquiátricos nos pais de crianças com TDAH. Isso ajuda a explicar por que o manejo em casa às vezes precisa considerar as dificuldades executivas de mais de uma pessoa na família ao mesmo tempo.", source: "Manual Barkley, cap. 4 (Comorbidades, Adaptação Familiar e Subtipos)" },
  { text: "No livro \"Vencendo o TDAH Adulto\", tratar o próprio TDAH é descrito como o primeiro passo antes de tentar aplicar qualquer estratégia de parentalidade — um adulto com funções executivas sobrecarregadas tem menos recursos disponíveis para sustentar regras e rotina com os filhos.", source: "Vencendo o TDAH Adulto (Barkley & Benton), Passo 5 — Paternidade/Maternidade" },
  { text: "A Regra 5 das oito regras cotidianas de Barkley e Benton é \"considere o futuro\": antecipar concretamente, com detalhes sensoriais, a sensação de já ter terminado a tarefa. Esse exercício mental usa a emoção como combustível motivacional, driblando a miopia temporal do TDAH.", source: "Vencendo o TDAH Adulto (Barkley & Benton), Passo 4 — Regra 5" },
  { text: "A Regra 6 do mesmo livro propõe \"decompor o futuro e torná-lo significativo\": fragmentar tarefas grandes em blocos pequenos, com alguém acompanhando o progresso e recompensa logo após cada etapa concluída — porque recompensa distante tem pouco poder de mover um cérebro com TDAH.", source: "Vencendo o TDAH Adulto (Barkley & Benton), Passo 4 — Regra 6" },
  { text: "Segundo Barkley e Benton, revelar o diagnóstico de TDAH no ambiente de trabalho só costuma valer a pena quando é necessário para conseguir adaptações formais — a decisão de contar ou não é estratégica, não uma obrigação moral.", source: "Vencendo o TDAH Adulto (Barkley & Benton), Passo 5 — Trabalho" },
  { text: "Cerca de três em cada quatro pessoas respondem bem já à primeira medicação estimulante testada, segundo o livro \"Vencendo o TDAH Adulto\" — mas o ajuste de dose é descrito como processo gradual e monitorado, não algo que se acerta de uma vez.", source: "Vencendo o TDAH Adulto (Barkley & Benton), Passo 3 — Medicação" },
  { text: "TDAH em crianças e TDAH em adultos não são o mesmo quadro clínico observado em espelho: o transtorno tem uma trajetória própria, passando por fases distintas da pré-escola à idade adulta, com sintomas que mudam de forma sem necessariamente diminuir de impacto.", source: "Manual Barkley, cap. 6 (Curso evolutivo)" },

  { text: "O modelo do livro descreve o TDAH como um freio (inibição comportamental) mais fraco, que compromete quatro funções executivas — a memória visual do tempo, a voz interna, o controle emocional e a capacidade de planejar. Entender essas quatro peças ajuda a enxergar o TDAH como um problema de desempenho no momento certo, não de conhecimento.", source: "Vencendo o TDAH Adulto, Passo 2" },
  { text: "TDAH não é falta de saber o que fazer — é \"miopia temporal\": dificuldade de organizar o presente em função de uma consequência que só vai aparecer no futuro. Por isso instrução e bom senso raramente bastam sozinhos.", source: "Vencendo o TDAH Adulto, Passo 2" },
  { text: "A Regra 1 do livro é simples de enunciar e difícil de praticar: pare a ação antes de agir ou falar. Respirar, repetir o que o outro acabou de dizer ou desacelerar a própria fala já cria a pausa que o freio natural não oferece sozinho.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 1" },
  { text: "A Regra 2 propõe olhar para trás antes de decidir: buscar na memória uma situação parecida já vivida serve de bússola para prever o que provavelmente vai acontecer agora. Sem esse olhar deliberado para o passado, cada decisão nasce do zero.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 2" },
  { text: "A Regra 3 pede para colocar em palavras — inclusive em voz alta, mesmo sozinho — o que foi visualizado sobre o passado e o futuro, extraindo dali uma regra prática para o momento. Verbalizar é o que transforma uma lembrança vaga em orientação de ação.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 3" },
  { text: "A Regra 4 é exteriorizar as informações fundamentais: lembretes físicos exatamente onde serão precisos, e um caderno ou diário sempre à mão. A informação que existe só na cabeça é a que mais escapa em um cérebro com TDAH.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 4" },
  { text: "A Regra 5 sugere antecipar emocionalmente a sensação de já ter terminado a tarefa, usando essa sensação como combustível para começar agora. Sentir o alívio da conclusão antes de fazer o trabalho ajuda a competir com a recompensa imediata de adiar.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 5" },
  { text: "A Regra 6 orienta fragmentar o futuro em blocos pequenos e significativos, com prestação de contas a outra pessoa e recompensa logo depois de cada etapa concluída — não só ao final do projeto inteiro.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 6" },
  { text: "A Regra 7 defende tornar os problemas externos, físicos e manuais: post-its, quadros, fichas — qualquer ferramenta que tire o problema de dentro da cabeça e o coloque em algo que se possa ver e manusear.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 7" },
  { text: "A Regra 8 é ter senso de humor: reconhecer o erro, explicar o que aconteceu, pedir desculpas quando cabe e seguir em frente, sem negação nem culpa excessiva. Humor autodepreciativo saudável é tratado como ferramenta de manejo, não como fraqueza.", source: "Vencendo o TDAH Adulto, Passo 4 · Regra 8" },
  { text: "Na educação, o livro recomenda técnicas como a leitura SQ4R e gravar aulas — formas de exteriorizar e reforçar o que a memória de trabalho verbal sozinha não sustenta. Um mentor com check-ins curtos e diários também substitui, de fora, a autorregulação que falta por dentro.", source: "Vencendo o TDAH Adulto, Passo 5 · Educação" },
  { text: "No trabalho, escolher carreira e ambiente compatíveis com o próprio perfil pesa tanto quanto qualquer técnica de organização. Reduzir distrações no espaço físico e contar com um mentor no trabalho são adaptações discretas que fazem diferença real.", source: "Vencendo o TDAH Adulto, Passo 5 · Trabalho" },
  { text: "Revelar o diagnóstico de TDAH no trabalho é uma escolha, não uma obrigação — o livro recomenda fazer isso apenas quando for necessário para conseguir uma adaptação formal, não como exposição automática.", source: "Vencendo o TDAH Adulto, Passo 5 · Trabalho" },
  { text: "Em dinheiro, a recomendação central é automatizar o que puder — pagamentos automáticos, orçamento visível — e considerar usar dinheiro físico em vez de cartão, porque o físico torna o gasto mais concreto e mais fácil de sentir na hora.", source: "Vencendo o TDAH Adulto, Passo 5 · Dinheiro" },
  { text: "Em casos financeiros mais graves, delegar a administração do dinheiro a outra pessoa não é fracasso — é reconhecer que algumas funções executivas comprometidas pedem apoio externo permanente, assim como óculos para quem não enxerga bem de longe.", source: "Vencendo o TDAH Adulto, Passo 5 · Dinheiro" },
  { text: "Em relacionamentos, sintomas de TDAH — esquecer, interromper, se distrair no meio de uma conversa — costumam ser mal-interpretados pelo outro como desinteresse ou grosseria. Nomear o que é sintoma ajuda o casal a discutir o problema real em vez de brigar por uma leitura errada de intenção.", source: "Vencendo o TDAH Adulto, Passo 5 · Relacionamentos" },
  { text: "Tratar o próprio TDAH melhora o relacionamento não por acaso: menos impulsividade e mais previsibilidade tiram do parceiro o papel de \"lembrete ambulante\" e devolvem espaço para a relação em si.", source: "Vencendo o TDAH Adulto, Passo 5 · Relacionamentos" },
  { text: "Na paternidade e maternidade, o primeiro passo recomendado pelo livro é tratar o próprio TDAH — é difícil sustentar rotina e regras para os filhos enquanto a autorregulação do adulto também está comprometida.", source: "Vencendo o TDAH Adulto, Passo 5 · Paternidade/Maternidade" },
  { text: "Regras familiares visíveis, combinadas previamente entre os pais, e um timer para checagem periódica dos filhos aplicam o mesmo princípio das 8 Regras à vida em casa: externalizar o que a memória não sustenta sozinha.", source: "Vencendo o TDAH Adulto, Passo 5 · Paternidade/Maternidade" },
  { text: "Na direção, o livro é categórico: nunca dirigir sem a medicação em efeito e zero álcool, porque a combinação de impulsividade e menor controle do freio comportamental eleva diretamente o risco de acidente.", source: "Vencendo o TDAH Adulto, Passo 5 · Direção" },
  { text: "Bloquear o celular ao dirigir e usar um lembrete físico para o cinto de segurança são exemplos de como transformar uma boa intenção (\"vou prestar atenção\") em uma barreira física que não depende de lembrar na hora.", source: "Vencendo o TDAH Adulto, Passo 5 · Direção" },
  { text: "Mais de 80% dos adultos com TDAH têm ao menos uma comorbidade — transtorno opositor, transtorno de conduta, ansiedade ou depressão. O livro é claro: tratar só o TDAH e ignorar a comorbidade deixa parte do sofrimento sem resposta.", source: "Vencendo o TDAH Adulto, Passo 5 · Comorbidades" },
  { text: "Cerca de 75% das pessoas respondem bem já ao primeiro estimulante testado, mas o ajuste de dose é um processo gradual e monitorado, não um resultado imediato. Esperar acerto de primeira tende a gerar frustração desnecessária.", source: "Vencendo o TDAH Adulto, Passo 3" },
  { text: "O livro usa critérios de avaliação mais rigorosos que o DSM-IV para adultos: sintomas presentes em três áreas (atenção/persistência, controle de impulsos, atividade excessiva), início antes dos 16 anos, e prejuízo em múltiplos domínios da vida — não bastam sintomas isolados em um único contexto.", source: "Vencendo o TDAH Adulto, Passo 1" },
  { text: "As cinco áreas problemáticas do dia a dia listadas no livro são gestão de tempo/metas, organização e memória operacional, autodisciplina/impulsividade, automotivação e concentração/prontidão. Reconhecer em qual dessas áreas a dificuldade pesa mais ajuda a escolher a regra certa para aplicar primeiro.", source: "Vencendo o TDAH Adulto, Passo 2" },
  { text: "A memória de trabalho verbal — a \"voz da mente\" — é o que permite formular regras próprias e manter a autoconversa que guia o comportamento. Quando ela é fraca, falar em voz alta o que se pretende fazer supre, de fora, o que essa voz interna não sustenta sozinha.", source: "Vencendo o TDAH Adulto, Passo 2" },
  { text: "A memória de trabalho não verbal — o \"olho da mente\" — é a capacidade de visualizar mentalmente o passado e o futuro. Sem ela funcionando bem, prever consequências vira um exercício abstrato em vez de algo que se \"vê\" antes de agir.", source: "Vencendo o TDAH Adulto, Passo 2" },
  { text: "Dificuldades de comunicação no TDAH têm raiz específica: memória de trabalho verbal fraca dificulta achar as palavras e manter uma sequência lógica ao explicar algo, enquanto planejamento fraco dificulta organizar ideias complexas na fala. Não é falta de inteligência, é uma engrenagem executiva específica.", source: "Vencendo o TDAH Adulto, seção sobre comunicação" },
  { text: "Repetir o que o interlocutor acabou de dizer antes de responder ganha tempo para organizar a resposta e ao mesmo tempo aplica a Regra 1 (pausa) e a Regra 3 (verbalizar) na prática de uma conversa real.", source: "Vencendo o TDAH Adulto, seção sobre comunicação" },
  { text: "Tomar notas ativamente durante uma reunião não serve só para lembrar depois — serve para manter o foco no momento presente, porque escrever exige um tipo de atenção que sustenta a atenção auditiva sozinha.", source: "Vencendo o TDAH Adulto, seção sobre comunicação" },
  { text: "O livro trata as 8 Regras como um conjunto interligado, não uma lista de escolha única: pausar (Regra 1) sem depois visualizar o passado (Regra 2) e verbalizar uma conclusão (Regra 3) deixa a pausa sem direção nenhuma para seguir.", source: "Vencendo o TDAH Adulto, Passo 4" },
  { text: "Antes de qualquer regra prática, o Passo 2 do livro insiste em conhecer e aceitar o próprio TDAH como ele é — negar o diagnóstico ou minimizar o impacto das funções executivas comprometidas tende a atrasar a busca por estratégias que realmente ajudam.", source: "Vencendo o TDAH Adulto, Passo 2" }
];

/**
 * Retorna o princípio do dia correspondente à data informada (ou hoje).
 * Usa o dia do ano (1-366) como índice, percorrendo toda a lista ao longo
 * do ano — como PRINCIPLES tem mais de 31 itens, o índice não pode mais
 * usar só o dia do mês (repetiria o mesmo item em datas próximas de meses
 * diferentes com menos de 31 dias). Ex: PRINCIPLES.length = 124 evita
 * repetição de padrão perceptível dentro do mesmo mês.
 * @param {Date} [date]
 * @returns {{text: string, source: string}}
 */
function principleForDate(date) {
  var d = date || new Date();
  var start = new Date(d.getFullYear(), 0, 0);
  var diff = d - start;
  var dayOfYear = Math.floor(diff / 86400000); // 1-366
  var index = (dayOfYear - 1) % PRINCIPLES.length;
  return PRINCIPLES[index];
}

export { PRINCIPLES, principleForDate };
